# example_pcre2bot.toml – pcre2bot's config file example
#
# References:
#   https://github.com/toml-lang/toml
#   https://metacpan.org/pod/TOML::Tiny
#
# Usage:
#   All keys values that expect a string must be quoted, i.e. nickname = 'pcre2bot',
#   but keys that expect a boolean integer value (1 = True; 0 = False), i.e. use_tls = 1.
#   To enable the logger, just set a path where the logs should be saved.
#
# Notes:
#   To connect to a server securely with TLS, the 'use_tls' key must be set to 1,
#   and 'port' set to a TLS port accepted by the server.
#   To connect with a self-signed certificate, both 'tls_cert' and 'tls_key' need
#   to be specified.
#   See:
#     https://libera.chat/guides/certfp
#     https://www.oftc.net/NickServ/CertFP/
#     https://stackoverflow.com/a/10176685

[server]

nickname    = 'pcre2bot'
username    = 'ryoskzypu'
ircname     = 'pcre2test IRC bot'
usermode    = '+IG'
server      = 'irc.libera.chat'
port        = '6697'
use_tls     = 1
tls_cert    = '/home/user/pcre2bot/tls/libera.cer'
tls_key     = '/home/user/pcre2bot/tls/libera.key'
log_path    = '/home/user/pcre2bot/irclogs'
log_private = 1
log_public  = 1
log_raw     = 0

# Hardcoding passwords in plaintext is bad practice, prefer to authenticate with
# a self-signed TLS certificate over a password.
#
# If a password is a must:
#   1. It can be set it with the --pass option, that accepts STDIN; so it will
#      prompt for the secret interactively. It can also be piped with a password
#      manager (e.g. pass libera/pcre2bot | pcre2bot -p).
#   2. Or set it in NICKSERV_PASS environment variable.
#
# All alternatives have preference over the password in config file.
nickserv_password = ''

# Auto-join channels
channels = [
    '#pcre2bot',
    '#ryoskzypu',
    '#regex',
]

# Userhosts lists (~user@host)
#
# List of the only userhosts that can address (allowed) or cannot address (ignored) pcre2bot.
# Note that the 'allow' list has priority over 'ignore'.

# Allowed
userhosts_allow = [
]

# Ignored
userhosts_ignore = [
]

# Authorized
#
# List of userhosts who are authorized to run !commands. Note that for security
# reasons, no one is authorized unless its userhost is on the list.
userhosts_auth = [
]

[pcre2test]

# Default options modifiers
pattern_modifiers = 'no_start_optimize,no_auto_possess,no_dotstar_anchor,utf'
subject_modifiers = 'ovector=0'

# Modifiers allow lists
#
# Lists of the only pattern/subject modifiers that are allowed in pcre2test.
# Note that single letter modifiers must not be concatenated, and a single empty
# value restricts all modifiers.

# Pattern
pattern_mods_allow = [
    'a',
    'g',
    'i',
    'm',
    'n',
    'r',
    's',
    'x',
]

# Subject
subject_mods_allow = [
    '',
]

# Pastebin services
#
# Notes:
#   - The services must accept HTTP POST requests with a file form field, and return
#     return a URL of its paste.
#   - Ethically the pastebin service should be hosted by the bot owner, otherwise
#     please respect free services and support them by making a donation.

# pcre2test's output
#
# Maximum number of lines allowed to be sent to chat, before uploading them to
# a pastebin service; and maximum number of lines allowed to be uploaded to a
# pastebin service.
max_irc_lines   = 5
max_paste_lines = 1000

primary_service = 'https://paste.c-net.org/'

fallback_services = [
    'https://0x0.st/',
]
